# Generated by Django 4.2.3 on 2023-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
